### ISSUE TITLE
SecurityGroup Hook does not allow creation of an SG for outbound rules only

### ISSUE THREAD

**Issue by networkprogrammer** [aws-cloudformation/aws-cloudformation-samples#73]
I am running into an issue where I need to create an SG for outbound only lambda communication. This hook causes a failure when creating such a rule.

```
Resources:
    InstanceSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupName: "Security Group"
            GroupDescription: "Lambda Traffic"
            VpcId: !Ref "VPCId"
            SecurityGroupEgress:
                - IpProtocol: "-1"
                  CidrIp: "0.0.0.0/0"
```
